from plugins.templateFileGeneration import TemplateGeneration


class GenerateRustRegisterMap(TemplateGeneration):
    """Generate Rust register map definitions"""

    FILE_ENDING = ".rs"
    BIT_DEFINE_STRING = "    pub const {2}: u32 = {1};\n"
    GENERAL_REGISTER_DEFINITION = "    pub const {0}: u32 = {1}; // {2}\n"
    REGISTER_BIT_INFORMATION = "    pub mod {0}_bits {{\n{1}    }}\n\n"
    COMPONENT_NAMING_AND_DEFINTION = "// IP Core Version: {1}\npub mod {0} {{\n{2}}}\n"
    AUTOGENERATION_HINT = "// This file is automatically generated, don't modify it!\n\n"

    def _format_const_name(self, name):
        """Convert name to Rust constant naming convention (SCREAMING_SNAKE_CASE)"""
        return name.upper().replace(" ", "_")

    def _extract_variable_name(self, temp_reg):
        """extract the register name if it has an alias. If it doesn't have a alias it will be called as original name generated in VHDL"""
        name = super()._extract_variable_name(temp_reg)
        return self._format_const_name(name)

    def _extract_register_information(self):
        """extraction of the slave register and all including bits"""
        return_string = ""
        keylist = sorted(self.parsed_file.register)
        for temp_reg in keylist:
            var_name = self._extract_variable_name(temp_reg)
            return_string += self.GENERAL_REGISTER_DEFINITION.format(
                var_name,
                self._calculate_register_offset(self.parsed_file.register[temp_reg].binary_coded[2:]),
                self._extract_read_write_option(self.parsed_file.register[temp_reg].option),
            )
            bit_def = self._extract_bit_defintion_rust(self.parsed_file.register[temp_reg].bit_definition)
            if bit_def:
                return_string += self.REGISTER_BIT_INFORMATION.format(var_name.lower(), bit_def)
        return return_string

    def _extract_bit_defintion_rust(self, key_value_pair):
        """extract the bits for a register and calculate / generate the bits"""
        return_string = ""
        key_value_pair = sorted(key_value_pair, key=self._get_key)
        for name, value in key_value_pair:
            shift_value = ""
            if len(value[0]) > 1 and isinstance(value[0], list):
                bit_value_list = [int(i) for i in value[0]]
                bit_list = range(min(bit_value_list), max(bit_value_list) + 1)
                shift_value = " | ".join(f"1u32 << {n}" for n in bit_list)
            else:
                shift_value = f"1u32 << {value[0]}"
            return_string += self.BIT_DEFINE_STRING.format(value[0], shift_value, self._format_const_name(name))
        return return_string

    def _write(self):
        """write the whole file"""
        self.output_file.write(self.AUTOGENERATION_HINT)
        out_string = self._extract_register_information()
        component_name = self.parsed_file.component_name.lower()
        self.output_file.write(self.COMPONENT_NAMING_AND_DEFINTION.format(component_name, self.parsed_file.ip_core_version, out_string))
