from plugins.templateFileGeneration import TemplateGeneration


class GenerateMarkdownRegisterMap(TemplateGeneration):
    """Generate Markdown documentation for registers"""

    FILE_ENDING = ".md"
    BIT_DEFINE_STRING = "| {0} | `{1}` | {2} |\n"
    GENERAL_REGISTER_DEFINITION = "### {0}\n\n**Address Offset:** `{1}`  \n**Access:** {2}\n\n"
    REGISTER_BIT_INFORMATION = "| Bit(s) | Mask | Name |\n|--------|------|------|\n{0}\n"
    COMPONENT_NAMING_AND_DEFINTION = "# {0}\n\n**IP Core Version:** {1}\n\n## Register Map\n\n{2}"
    AUTOGENERATION_HINT = "<!-- This file is automatically generated, don't modify it! -->\n\n"

    def _extract_register_information(self):
        """extraction of the slave register and all including bits"""
        return_string = ""
        keylist = sorted(self.parsed_file.register)
        for temp_reg in keylist:
            return_string += self.GENERAL_REGISTER_DEFINITION.format(
                self._extract_variable_name(temp_reg),
                self._calculate_register_offset(self.parsed_file.register[temp_reg].binary_coded[2:]),
                self._extract_read_write_option(self.parsed_file.register[temp_reg].option),
            )
            bit_info = self._extract_bit_defintion(self.parsed_file.register[temp_reg].bit_definition)
            if bit_info:
                return_string += self.REGISTER_BIT_INFORMATION.format(bit_info)
            return_string += "\n"
        return return_string

    def _write(self):
        """write the whole file"""
        self.output_file.write(self.AUTOGENERATION_HINT)
        out_string = self._extract_register_information()
        self.output_file.write(self.COMPONENT_NAMING_AND_DEFINTION.format(self.parsed_file.component_name, self.parsed_file.ip_core_version, out_string))
